### ISSUE TITLE
rechain_block的作用

### ISSUE THREAD

**Issue by zeninpalm** [xumingming/crowbar#1]
Hi! 我也在看这本书，这个函数的作用是在unchain_block之后，如果反悔了，可以把这个block在放回原来的位置去

**Comment by xumingming** [comment]
赞，以后可以多交流，你是怎么找到我这个 repo 的？

**Comment by zeninpalm** [comment]
哈哈！纯属巧合，我就是搜了一下crowbar，就找你的repo了！
